# src/core/solo_cmt_plan.py

"""
solo_cmt_plan.py

Purpose:
- Experimental commit plan
- FORCE all behaviors into a single commit

This module is intentionally simple and deterministic.
"""

def plan_single_commit(behaviors: list, report=None) -> list:
    """
    Force all behaviors into exactly one commit.

    Parameters
    ----------
    behaviors : list[str]
        Behavior sequence generated by beh_layout
    report : callable or None
        Optional logger (e.g. print)

    Returns
    -------
    commit_batches : list[list[str]]
        Always a list with exactly one batch
    """

    if report:
        report("[solo_cmt_plan] force single commit")

    # One commit, containing all behaviors
    return [list(behaviors)]
